version: '3.7'

services:
  app:
    build: .
    command: yarn dev
    container_name: validator-boleto
    ports:
      - 8080:8080
    environment:
      DB_NAME: "PORT"
    volumes:
      - .:/app